name: DotaMine
version: 0.1
author: rfsantos1996
main: com.jabyftw.dotamine.DotaMine
description: Dota on Minecraft!
depend: [ControllableMobsAPI]
softdepend: [Vault]
commands:
   dota:
     description: Main command
     permission: dotamine.dota
     usage: Use /dota help
   join:
     description: Join command
     permission: dotamine.play
     usage: Use /join
   spectate:
     description: Spectate command
     permission: dotamine.spectate
     usage: Use /spectate
permissions:
   dotamine.dota:
     description: Gives access to dota command
     default: true
   dotamine.play:
     description: Gives access to join command
     default: true
   dotamine.spectate:
     description: Gives access to spectate the game on join
     default: true
   dotamine.forcestart:
     description: Allows you to break blocks
     default: op